### ISSUE TITLE
recipe for target 'kollector.recruited_pe.fastq' failed

### ISSUE THREAD

**Issue by conchoecia** [bcgsc/kollector#12]
Hello,

I am trying `kollector` for a single transcript. It looks like it made it through the tagging phase but the make recipe for recruit failed. Any idea what could have happened, or could you possibly add a trace to the shell script?

Thank you-

```
Currently Reading Read Number: 120000000        Unique k-mers Added: 9243       Reads Used in Tagging: 119
K-mer threshold reached at read 122051845
Storing filter. Filter is 18032 bytes.
Filter Creation Complete.
biobloomcategorizer -p kollector_BBT -t 90 -d kollector_BBT -f kollector_BBT.bf -s 0.50 -e -i <(zcat -f -- 10x_trim_1.fastq.gz) <(zcat -f -- 10x_trim_2.fastq.gz) >> kollector.recruited_pe.fastq
Min score threshold: 0.5
Usage of paired end mode:
BioBloomCategorizer [OPTION]... -f "[FILTER1]..." [FILEPAIR1] [FILEPAIR2]
or BioBloomCategorizer [OPTION]... -f "[FILTER1]..." [PAIREDBAMSAM]

/usr/local/bin/kollector/bin/kollector-recruit.mk:63: recipe for target 'kollector.recruited_pe.fastq' failed
make: *** [kollector.recruited_pe.fastq] Error 1
make: *** Deleting file 'kollector.recruited_pe.fastq'
Command exited with non-zero status 2
=> kollector.sh: 738.00 kollector-recruit.mk name=kollector seed=kollector_reference.fa pe1=10x_trim_1.fastq.gz pe2=10x_trim_2.fastq.gz s=0.50 r=0.7 n=10000 j=90 k=25
```

**Comment by KristinaGagalova** [comment]
Hi, could you please send the version of Biobloom tools? Command below
```
biobloomcategorizer --version
```

**Comment by JustinChu** [comment]
I changed -d in the newest version of BBT but forgot to update kollector.

Try this branch and let me know if there are any issues:
https://github.com/bcgsc/kollector/tree/BBT_210

**Comment by conchoecia** [comment]
@KristinaGagalova here is the version:

```
biobloommaker (BIOBLOOMTOOLS) 2.1.0-1-g19ea
Written by Justin Chu.
```

Will try the new branch and will update after. Thanks!

**Comment by conchoecia** [comment]
Looks like it worked. Here is the output of stdout and stderr. Unfortunately it didn't find a path to assemble my single locus that I passed. 

[kollector.log](https://github.com/bcgsc/kollector/files/1684156/kollector.log)

**Comment by JustinChu** [comment]
1826 read pairs were recruited, assuming it was ~10000bp and 2x150bp reads you have around ~50x raw coverage, but the assembly was heavily fragmented. I suspect that our assembly k, r and s are somewhat not well optimized. What sort of genome did you try this on?

@KristinaGagalova You have more experience running kollector. Any suggestions on assembly k, r and s that seem to be best for single targets?

**Comment by KristinaGagalova** [comment]
Hi, 
It will be more useful to have some insights on the genome or species. 
I can give you some advises but this is just a general approach. 

1) I see that your reads are trimmed, trimming for low quality bases improves the quality of the recruited kmers. 
2) You can try to run again with slightly lower r and s (n looks fine), but do not go very low since you will recruit off target reads (something like r=0.6 and s=0.4 could work) 
3) The k you have used for the assembly is quite low (k=32). In this case I don't know what type of genome is this, you can use the k that is used for the genome assembly (if you have this info) 
4) Another good advise is to get the longest assembled contigs from the first kollector run, let's say take the contigs with coverage >= 40-50% and do another run of kollector, this time using the original target + the partial contigs.

I hope this helps!

**Comment by conchoecia** [comment]
Thanks for your input @KristinaGagalova and @JustinChu. This is from an outbred marine invertebrate, so it is likely that the heterozygosity is very high. I may do some more quality trimming, and will definitely try a larger k. Just curious - why do you use an even-number kmer for the default for `kollector`? Seems like you would want to stick with an odd kmer size to avoid palindromes.

**Comment by JustinChu** [comment]
Hi Conchoecia,

Sorry for the late reply.

In terms of the k-mer question it is more of an AbySS question, but here is my crack at it:
The need for odd k-mer was only due to Velvet’s implementation of de Bruijn graphs assembly, and the problem arose because even k-mers can cause self-connections in the assembly graph. However, the fact that each edge can be converted to a vertex with length k+1 (k-mer plus the 1 base extension) which can result in a palindromic edge, which must also be dealt with anyway. Furthermore, if palindrome does exist longer than the k-mer length you can expect the graph to fold on itself due anyway unless path logic is in place to prevent this. In the case of ABySS there is graph traversal logic that can deal this issue regardless if the k-mer does connect with itself due to palindromes.
