### ISSUE TITLE
Error message... gzip: stdout: Broken pipe

### ISSUE THREAD

**Issue by stevemmarshall** [bcgsc/kollector#18]
Hi

I tried to run the test example and got this error message.. I'm installed the package via linuxbrew

<img width="1071" alt="error_message" src="https://user-images.githubusercontent.com/18666723/44070075-c9062942-9f4f-11e8-98e8-632eddb1b73b.png">

thanks
steve

**Comment by JustinChu** [comment]
Sorry about this, I still need to update the Linuxbrew version of BBT (unfortunately I am having trouble with fixing a compilation on mac os so it was put on the back burner). In the meantime can you download version 2.1.x version of BBT and install it?This should fix the problem.

Sorry for the inconvenience.

**Comment by stevemmarshall** [comment]
Thanks Justin, it seems to be working now... 

What's your recommendation on max k-mer size? I'm using an Ig transcript from hamster as my guided target and have a paired end unstranded sample with > 100M reads...

cheers
steve

**Comment by JustinChu** [comment]
K-mer size for abyss is usually dependant on your data (read length etc.). I'd suggest doing a sweep if you have the time, otherwise, if you have 150 bp you can try up to k128 or if you have 100 try up to k80.

Do you mean `max k-mers` (`-n`)? It refers to the number of k-mers that we will consider before assembling.

If you mean `-n` this should be set to how long you expect your target to be roughly + the read error expected. Rule of thumb: (average gene length)x(number of genes in run)x(multiplier for error). A conservative multiplier would be 1.5 to 2x.

**Comment by stevemmarshall** [comment]
Hi Justin

Thanks for the rough guidelines... my read lengths ~ 250bp... I expect my target somewhere 500bp-1Kb

cheers
steve

**Comment by JustinChu** [comment]
I haven't run a lot of 250bp data.
@benvvalk do you have any suggestions on k-mer ranges to try at this size?

**Comment by benvvalk** [comment]
@JustinChu k=112 was our optimal on the (uncorrected) read set from the ABySS 2.0 paper (GIAB NA24143), which was 250bp reads.  k=112 was the optimal for both MPI and Bloom filter assembly modes.

**Comment by stevemmarshall** [comment]
Thanks @benvvalk and @JustinChu
