### ISSUE TITLE
Error running abyss assembly

### ISSUE THREAD

**Issue by TomHarrop** [bcgsc/kollector#19]
Hi,

I'm trying to run kollector.sh but I'm getting an error at the abyss step.

My command is:

`kollector.sh -j 8 csd_tx.fasta REUd10_1.fastq REUd10_2.fastq`

Here is the error (i've removed the full paths)
```
-----------------------------------------
Running ABySS assembly...
-----------------------------------------
make: Entering directory '/path/to/kollector.abyss'
/usr/bin/mpirun -np 8 ABYSS-P -k32 -q3 -v   --coverage-hist=coverage.hist -s kollector-bubbles.fa  -o kollector-1.fa ../kollector.recruited_pe.fastq 
--------------------------------------------------------------------------
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       tom
Executable: ABYSS-P
--------------------------------------------------------------------------
8 total processes failed to start
/usr/local/bin/abyss-pe:546: recipe for target 'kollector-1.fa' failed
make: *** [kollector-1.fa] Error 134
make: Leaving directory '/path/to/kollector.abyss'
Command exited with non-zero status 2
=> kollector.sh: 0.18 abyss-pe -C kollector.abyss v=-v k=32 name=kollector np=8 lib=pet pet=../kollector.recruited_pe.fastq long=longlib longlib=../kollector_reference.fa
```
This is kollector release 1.0.1 built on the `bsgsc/abyss:latest` docker image, which doesn't have a tag, but I think it's version 2.1.0.

Any suggestions on troubleshooting this?

**Comment by JustinChu** [comment]
Seems more to be an abyss issue.
@benvvalk do you have any idea what is happening?

**Comment by benvvalk** [comment]
@TomHarrop Did you compile ABySS from source?

The error suggests that `ABYSS-P` is not found on your PATH.  (`ABYSS-P` is an MPI-based de Bruijn graph assembly program.)  The most common reason for `ABYSS-P` to be missing is because the ABySS `configure` step could find an MPI library and/or header files installed on the system.  In this case, compilation of `ABYSS-P` will be skipped, but all of the other ABySS programs will be compiled/installed as usual.

You will somehow need to get OpenMPI (and the associated development header files) installed on your target machine(s).  If you don't have admin privileges or can't get your IT team to do it, you could use `linuxbrew` to install it, or failing that, you could also build it from source.  We have had some issues recently with OpenMPI >= 3.0, so we recommend installing OpenMPI version < 3.0.

**Comment by benvvalk** [comment]
@TomHarrop You can test that is MPI is correctly installed by looking at the results of the MPI tests in the output of the `configure` command.

**Comment by TomHarrop** [comment]
Thanks @benvvalk, I managed to get `ABYSS-P` to compile using
```
./configure --with-mpi=/usr/lib/x86_64-linux-gnu/openmpi
```
I was using the ABySS docker image (https://hub.docker.com/r/bcgsc/abyss/), so `ABYSS-P` is missing there too. In the dockerfile it looks like OpenMPI is installed, but the location is not correct when ABySS is configured: https://github.com/bcgsc/abyss/blob/745e4a5aba0a273de2da7216a1b07a9fb29d5e6b/Dockerfile#L13

Cheers!

**Comment by benvvalk** [comment]
@TomHarrop Great, glad you got it working, and thanks for the heads up about the Docker image!
