### ISSUE TITLE
test-kollector_assembledtargets.fa is empty

### ISSUE THREAD

**Issue by auesro** [bcgsc/kollector#29]
Dear all,

I am testing Kollector for the first time and decided to go check if everything worked out. 
I got one error that I could fix: `[E::main_mem] fail to open file 'test-kollector_reference.fa'.` . I fixed this by adding this line to the `kollector.sh` file: `cp $seed_symlink $abyss_dir/` after `mkdir -p $abyss_dir` so that `bwa mem` will find the `_reference.fa` file (located one folder upstream). Then the program proceeded normally I guess.
But after it completed (with `Testing Kollector completed.`) I find that the `test-kollector_assembledtargets.fa`, `test-kollector.transcript2assembly.sam` and `test-kollector_hitlist.txt` are empty (zero bytes).

I add here the [log file](https://www.dropbox.com/s/uuwz5umodqnot9x/celegans-kollector.log?dl=0) and [summary file from BBT](https://www.dropbox.com/s/gtvve6lzvqnk4af/test-kollector_BBT_summary.tsv?dl=0) in case they are useful.

Any ideas?

Thanks a lot,

A

**Comment by lcoombe** [comment]
Hello @auesro,

Just looking at your log, it appears that after your fixing the reference fa file the pipeline didn't start back at the beginning? Ie. It started partway through the assembly step. This could be an issue if there were problems accessing files in earlier steps. Could you try cleaning up your working directory and launching the pipeline again, ensuring it starts at the very beginning? To be clear, you are running the test in the `test` directory?

I just tested on my side, and that extra `cp` command shouldn't be needed, since the `kollector.sh` file creates a symlink to the given target file with:
```
#symlink files
seed_symlink="${prefix}_reference.fa"
ln -s -f $seed $seed_symlink
```
then, ABySS would have access to the file in this directory with (note that the longlib variable points to the parent directory of $abyss_dir): 
```
        time_command abyss-pe -C $abyss_dir v=-v k=$k name=$prefix np=$j  lib='pet' pet=$abyss_input long='longlib' longlib=../$seed_symlink
```
I'm wondering if there was a broken link or something similar in your execution? If you clean-up the files and restart the whole process from the beginning, and still see an issue, do follow-up with that log.

Thank you for your interest in Kollector!
Lauren

**Comment by auesro** [comment]
Hi @lcoombe ,

Thanks a lot for your help. I removed the mentioned cp command (but have also reinstalled everything from scratch, this time using conda instead of brew) and it worked perfectly for the test!

I close this as it is solved!

Cheers,

A

**Comment by lcoombe** [comment]
Great, I'm glad it's all working for you now!
